# yaml-language-server: $schema=https://json.schemastore.org/pyproject.json
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "testing-apis"
version = "0.0.0"
description = "Testing REST APIs either for personal projects or for work."
authors = [{name = "billwallis"}]
readme = "README.md"
license-files = ["LICENSE"]
requires-python = ">=3.13"
dynamic = ["dependencies"]

[dependency-groups]
dev = [
    "poethepoet>=0.46.0",
    "pre-commit>=4.6.0",
]
test = [
    "covdefaults>=2.3.0",
    "coverage>=7.13.5",
    "pytest>=9.0.3",
]


# For some reason, setuptools doesn't like the editable syntax :sob:
#[tool.setuptools.dynamic]
#dependencies = {file = ["requirements.txt"]}


[tool.poe]
verbosity = -1
envfile.optional = ".env"

[tool.poe.tasks]
install.shell = """
    pip install --editable . --requirement requirements.txt
    pip install --editable . --group dev --group test
    pre-commit install --install-hooks
"""
test.shell = """
    coverage run -m pytest -vvv
    coverage xml --quiet
    coverage report --no-skip-covered --include 'projects/*/tests/*'
    coverage report --no-skip-covered --include 'projects/*/src/*'
"""
add.shell = """
    python -m tools.src.tools.add ${name}
"""
add.args = [
    {name = "name", positional = true, required = true},
]

[tool.poe.tasks.lint]
control.expr = "sys.platform"

[[tool.poe.tasks.lint.switch]]
case = "win32"
shell = """
    echo '=== pre-commit checks ==='
    SKIP=identity pre-commit run --all-files --hook-stage pre-commit
    echo '=== pre-push checks ==='
    SKIP=identity pre-commit run --all-files --hook-stage pre-push
"""

[[tool.poe.tasks.lint.switch]]
shell = """
    echo '\\033[0;34mpre-commit checks\\033[0m'
    SKIP=identity pre-commit run --all-files --hook-stage pre-commit
    echo '\\033[0;34mpre-push checks\\033[0m'
    SKIP=identity pre-commit run --all-files --hook-stage pre-push
"""


[tool.pytest.ini_options]
testpaths = ["projects/*/tests"]

[tool.coverage]
run.source = [
    "projects/alteryx_gallery/src",
    "projects/alteryx_gallery/tests",
    "projects/amex/src",
    "projects/amex/tests",
    "projects/braze/src",
    "projects/braze/tests",
    "projects/companies_house/src",
    "projects/companies_house/tests",
    "projects/confluence/src",
    "projects/confluence/tests",
    "projects/dataiku/src",
    "projects/dataiku/tests",
    "projects/gmail/src",
    "projects/gmail/tests",
    "projects/google_sheets/src",
    "projects/google_sheets/tests",
    "projects/jira/src",
    "projects/jira/tests",
    "projects/metabase/src",
    "projects/metabase/tests",
    "projects/microsoft_teams/src",
    "projects/microsoft_teams/tests",
    "projects/new_relic/src",
    "projects/new_relic/tests",
    "projects/notion/src",
    "projects/notion/tests",
    "projects/quorum_oda/src",
    "projects/quorum_oda/tests",
    "projects/sainsburys_store_locator/src",
    "projects/sainsburys_store_locator/tests",
    "projects/slack/src",
    "projects/slack/tests",
    "projects/tableau/src",
    "projects/tableau/tests",
    "projects/tempo/src",
    "projects/tempo/tests",
    "projects/tfl/src",
    "projects/tfl/tests",
    "projects/twilio/src",
    "projects/twilio/tests",
    "projects/vault/src",
    "projects/vault/tests",
    "projects/wunderground/src",
    "projects/wunderground/tests",
]
run.plugins = ["covdefaults"]  # https://youtu.be/70T6OxKwxm0
report.fail_under = 10
report.exclude_lines = [
    "@pytest.mark.skip",
    "@pytest.mark.xfail",
]
